version: '3.8'
services:
  nginx:
    image: nginx   
    container_name: nginx 
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
      - type: bind
        source: ./nginx/conf/nginx.conf
        target: /etc/nginx/conf/nginx.conf
      - type: bind
        source: ./nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - default

  php:
    image: php:7-fpm-alpine
    container_name: php
    volumes:
    - type: bind
      source: ./html
      target: /var/www/html

networks:
  default:
    external: 
      name: nginx-php